### ISSUE TITLE
Add ability to import POIs, routes

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/whogo-maps#1]
At least from a GPX file.

**Comment by jaykijay** [comment]
If this is added, maybe add the ability to export a driven route to gpx, too.
I think when working with gpx files, this would be not many work to add :)
Thanks

**Comment by rigow** [comment]
I would very much like to see the import of gpx files. modrana does it already (see logs) It allows to create nice routes for my motorbike with all those online services and run them offline while driving.
