### ISSUE TITLE
Restore passive maneuver icons

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/whogo-maps#10]

**Comment by otsaloma** [comment]
@rinigus Are filters supported? I'm trying the following, but as soon as I define any kind of a filter, I see none of the points.

```qml
var params = {
    "type": "circle",
    "source": map.sourceManeuvers,
    "filter": ["==", "passive", false],
};
map.addLayer(map.layerManeuvers, params);
```

The passive property is currently only used by public transport routing to indicate stops that are passed, while an active maneuver is the stop where you get off. I want subtle markers for the passive maneuvers and figured I'd use separate layers with filters. Or, are [expressions](https://www.mapbox.com/help/mapbox-gl-js-expressions/) supported?

**Comment by rinigus** [comment]
Filters should be supported, expressions are bit trickier - I have seen that many of them are not there yet for Mapbox GL Native (JS is ahead).

Would you mind to test whether setting filter as a string would work? I cannot find a place right now, but I suspect that it could need that in such notation
```
 var params = {
    "type": "circle",
    "source": map.sourceManeuvers,
    "filter": '["==", "passive", false]',
};
map.addLayer(map.layerManeuvers, params);
```

If it doesn't work, I'll have to look into it.

**Comment by otsaloma** [comment]
I tried the string trick, but got `Unable to add layer: filter expression must be an array`.

**Comment by rinigus** [comment]
Thanks for testing. Looks like the syntax was right before then. Its possible though that there is some issue with `true` / `false` notations. I have searched my styles and I don't have any filter like that (mainly >= or `has`). Maybe we can transfer the value to `0` and `1` and check then?

But I'll look into it. I'll try to make some demo and see if it works over here.

**Comment by otsaloma** [comment]
It doesn't seem to be a problem with boolean values, even simple things like `["has", "passive"]` or `[">", "duration", 0]` result in nothing shown.

**Comment by rinigus** [comment]
Filters do work. I made a test with the following code and it worked as expected (showing blue dot only next to P3, see below):

```javascript
            var points = [
                        QtPositioning.coordinate(60.16, 24.94),
                        QtPositioning.coordinate(60.17, 24.95),
                        QtPositioning.coordinate(60.18, 24.96)
                    ]
            var names = [ "P1", "P2", "P3" ]
            map.addSourcePoints("points", points, names)

            var params = {
                "type": "circle",
                "source": "points",
                "filter": ["==", "name", "P3"],
            };

            map.addLayer("points-centers", params)
            map.setPaintProperty("points-centers", "circle-radius", 5)
            map.setPaintProperty("points-centers", "circle-color", "blue")

            map.addLayer("points-label", {"type": "symbol", "source": "points"})
            map.setLayoutProperty("points-label", "text-field", "{name}")
            map.setLayoutProperty("points-label", "text-justify", "left")
            map.setLayoutProperty("points-label", "text-anchor", "top-left")
            map.setLayoutPropertyList("points-label", "text-offset", [0.2, 0.2])
            map.setPaintProperty("points-label", "text-halo-color", "green")
            map.setPaintProperty("points-label", "text-halo-width", 2)
```

So, I think something is wrong with the point data, in particular with the properties associated with the points. 

In the test case, I used  `addSourcePoints` that ends up calling `QQuickItemMapboxGL::updateSourcePoints` at https://github.com/rinigus/mapbox-gl-qml/blob/master/src/qquickitemmapboxgl.cpp#L540 . As you could see, it makes feature collection that has names associated with each point separately. Something similar has to be done in QML when you add `passive` property using more general `addSource` method of the map widget.

**Comment by otsaloma** [comment]
Ah, I didn't even notice the `names` argument to `updateSourcePoints`, I though I was handling the whole maneuver object and had all properties available. Now, if I convert the passive (true/false) property to name ("active"/"passive"), it works as expected.
