### ISSUE TITLE
Use pitch when navigating

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/whogo-maps#11]
Only for vector sources? Configurable in the preferences page?

**Comment by rinigus** [comment]
Great to see it in the plans. I would expect to have the maximal angle set by user and ability to enable / disable it. 

With such options you would probably don't have to concern yourself with the type of map source.

**Comment by otsaloma** [comment]
I just tested this and it looked to me like the maximum angle of 60 is suitable, maybe I'd want to set it even higher, but not lower. So, do you have a real need for the angle setting?

**Comment by rinigus** [comment]
I don't need as such. In this sense, it would be correct to test without and see whether there is a wish to set it to something smaller. As far as I remember, it was configurable on similar Android apps. But I haven't used them for a while, so I could be wrong. 

From the POV of minimal and right settings, let's give it a go at 60. 60 degrees is constraint from QMapboxGL, cannot go further according to the docs of `pitch`.
