### ISSUE TITLE
Cartago Streets missing text and icons

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/whogo-maps#12]

**Comment by otsaloma** [comment]
![Screenshot](https://user-images.githubusercontent.com/237265/36637471-0bb914d4-19e5-11e8-8308-5111d5fc401a.png)

![Screenshot](https://user-images.githubusercontent.com/237265/36637473-0e9039bc-19e5-11e8-89a9-03ec920e7e75.png)

Labels and POI icons are missing on higher zoom levels. @rinigus: is this the same [issue](https://github.com/otsaloma/cartago-styles/issues/3) we discussed earlier?

For comparison: http://cartago.io/maps/vector/#15.42/60.1968/24.8829

Tram tracks seem missing too. And dotted lines of footways look bad.

**Comment by rinigus** [comment]
Yes, it's exactly the same issue as before. It's fixed upstream and there is a Qt release available with it. Unfortunately , that release is hit by https://github.com/mapbox/mapbox-gl-native/issues/10644 . So, I am waiting for the next release or at least up to date Qt branch that is used for compilation of Sailfish version.

I think fixing Cartago style would be hard since you don't have full control or at least overview of data in the tiles.

**Comment by rinigus** [comment]
Two days ago, QMapboxGL  https://github.com/mapbox/mapbox-gl-native/tree/qt-staging has been bumped to more recent version. This should include the fixes to the bugs we have been mentioning above. I'll wait few days, maybe they will push out new release with these changes. Then I can start testing Mapbox QML plugin with it.

**Comment by rinigus** [comment]
@otsaloma, MapboxGL has been updated yesterday to qt-1.3.0 version and I have compiled it with the corresponding update at OBS. I could see all the icons for Cartago as well using this version.

You could get the RPM now from http://repo.merproject.org/obs/home:/rinigus:/maps:/devel/sailfish_latest_armv7hl/armv7hl/ (there is similar repo for i486). So far I have not seen any bugs with it, but it should be tested before full official release.

**Comment by otsaloma** [comment]
Thanks! We're getting close to an initial release. I'm still doing some cleanup and minor changes, so I'll be testing as I go along. This shouldn't take long anymore, I'll ping you if I'm done before you get a new release out, as I'd want at least the pan threshold fix out before I make a release.
