### ISSUE TITLE
Add search autocomplete

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/whogo-maps#2]
Previous discussion: https://github.com/otsaloma/poor-maps/issues/5

**Comment by otsaloma** [comment]
Time for a status update.

* Digitransit (Pelias, Finland only) seems to support autocomplete.

* OpenCage doesn't support autocomplete.

* OSM Scout: @rinigus ?

* Photon supports autocomplete, but has only an unstable demo server.

Shame Mapzen died, as Pelias was good for this. The only Pelias service that has sprung up that I see is [geocode.earth](https://geocode.earth/) offering invites for $200/mo minimum...

Benefit seems limited, but I'll likely do this next (1.1) anyway.

**Comment by rinigus** [comment]
OSM Scout: It doesn't support it intentionally, it will just search again and again. No idea how fast/slow its in practice. However, I can later look into it and optimize for autocomplete.

geocode.earth: I have been contacted by them few days ago regarding possible collaboration and we will have a chat sometime next week. I will ask them if they can come up with the scheme that would allow open-source projects to use their service. Maybe they can charge user directly? 

And maybe they can give some tips on how to implement autocompletion in OSM Scout Server. Its Pelias developers which started that company and they have experience with libpostal that seems to me a possibly problematic part in auto-complete.

**Comment by otsaloma** [comment]
In addition to speed, autocomplete requires that matches are found by partial strings, e.g. searching for "Mann" should return "Mannerheimintie", when biased for a search done in Helsinki. I don't know how your geocoder works, but for short strings it might be non-trivial to provide a sensible set of such matches.

And nice to hear about geocode.earth, feel free to contact me privately if there's some potential for cooperation. I understand that providing a service costs money, but their listed pricing is impossible for a hobby project.

**Comment by rinigus** [comment]
It is able to search partial strings. The problem that will happen is related to parsing address by libpostal. But otherwise, substring search happens already now.

Re direct contact: sure. I'll ask about it.

**Comment by otsaloma** [comment]
Done, see commits on July 14th.

**Comment by rinigus** [comment]
I presume this is related to the geocoder, not nearby types PR (https://github.com/otsaloma/whogo-maps/pull/40)? I will look into it and will try to add OSM Scout Server support as well. Will ask if something is not clear.

**Comment by otsaloma** [comment]
This issue is about the geocoder autocomplete, but I added autocomplete for nearby guide venue types as well, see the commits on July 19th. I added support for it in Foursquare, but there's still some details to work out, I'll ping you on that PR when done, the intention is that it should be usable in your case too.
