### ISSUE TITLE
Lack of overlay support, nautical maps

### ISSUE THREAD

**Issue by Olf0** [otsaloma/whogo-maps#31]
WhoGo Maps currently lacks (technically) overlay maps, respectively (by functionality) nautical maps ("sea marks").  Poor Maps provides them (both).
Although it may be not trivial to correctly overlay a vector base map with a raster overlay map, OSMand~ (under Android) does that nicely.

P.S.: Personally, WhoGo Maps' current inability to display nautical markings constitutes a regression compared to Poor Maps.

**Comment by otsaloma** [comment]
Technically it should be possible to have overlays with Mapbox GL, but I removed support for them on purpose. Raster overlays never made much sense, but by now with vector maps and HiDPI screens and overlays still at `@1x` scale, it just made no sense anymore at all. Once there's some actual sensible provider, we can evaluate what kind of support is needed and add it.

**Comment by Olf0** [comment]
@otsaloma, I cannot counter your points on technical grounds, but this functionality is simply missing in WhoGo Maps.  Plus, as WhoGo / Poor Maps is your baby, I am just trying to provide you with a user's perspective.

BTW, OSMand~ provides vector (e.g. the "sea marks") and raster overlays ("hike & bike", satellite pictures etc.) over a vector base map, while Poor Maps and modRana provide raster overlays ("sea marks" rsp. all maps) over a raster base map, and all three are working and looking really fine.
Moreover these overlay maps provide functionality, which I am regularly using (presumably others, too).

The use of vector maps in WhoGo Maps is really cool, but IMHO that should not come with a loss of functionality, which in turn makes WhoGo Maps less attractive.
Thus I kindly ask you to reconsider your decision to wait, until a proper provider of vector overlay maps appears.
