### ISSUE TITLE
Allow toggling voice navigation while navigation is active

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/whogo-maps#32]
i.e. get rid of the `enabled` below.

https://github.com/otsaloma/whogo-maps/blob/884ed83667b64473e30f898267c8e8e4f75d26d7/qml/NavigationPage.qml#L203-L209

I just don't quite remember why this needed to locked – @rinigus: your code, do you remember? Given the pregeneration, turning it on might have a slight delay, but that should be no big deal, and turning it off would still serve previously generated audio, but we can add a simple check on the QML side to ignore those. Anything else?

**Comment by rinigus** [comment]
@otsaloma - not from the top of my head. I will look tonight and see why was it. I can only speculate that its due to the lag in generation of sound files, but I'll have to check the details. Let me come back to you with it.

**Comment by rinigus** [comment]
Looked into the code a bit. If we want to do it on-fly, we'll have to call map.initVoiceNavigation . Other than that, I don't see why it shouldn't work. As you pointed out, we have verbal instructions anyway and user should expect some small delay...

While reading through the source, I could see that rerouting messages are created at each call of `_get_voice_uri`. In reality, its cached and not regenerated, but we could still move them maybe into `set_voice`

**Comment by otsaloma** [comment]
OK, I'll do this via a PR and ping you when done so you can look it over too.

**Comment by rinigus** [comment]
Will be happy to.

**Comment by otsaloma** [comment]
This looked straight-forward, so I skipped the PR. Anyway, you can look over those two commits. As far as I can tell there's just three things needed:

1. Don't play sound if voice navigation off (added, first commit)

1. Don't generate new WAVs if voice navigation off (already existed)

1. Reinitialize the voice generator if toggled on while navigation is active (added, second commit)
