### ISSUE TITLE
Make recentering when navigating smoother

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/whogo-maps#34]
> I said earlier that the animations are smooth and so they are, but the little symbol that shows your position keeps jumping forward and back. It looks like it is moving along the map and when too far, then the whole map including the symbol is jerked back. It is not too distracting but noticeable.

https://talk.maemo.org/showpost.php?p=1543039&postcount=66

**Comment by rinigus** [comment]
When I dropped coordinate animation for re-centering during navigation (https://github.com/rinigus/whogo-maps/commit/dcd9ebad8cbfae6e137d13c4bfdccba0f424cd75), the jump of the position almost disappeared. There is a small jump induced by _dt_ between location and map center update, but its significantly smaller in terms of amplitude than before.

The corresponding commit will be a part of the navigation GUI PR, when we'll get the map matching PR cleared.
