### ISSUE TITLE
Russian translation fixed post 1.0 release

### ISSUE THREAD

**Issue by dikonov** [otsaloma/whogo-maps#39]
I was not able to see the translation in action before the release and it contained some strings that were too long to fit the screen. These have been shortened and 2 new strings translated (see Transifex). **Please, update**
![20180613013525](https://user-images.githubusercontent.com/4271322/41320914-5a8977e2-6eaa-11e8-8a2e-af5126c575e1.jpg)
 
Misc issues:
- km / m  should be translatable
- Types of venues (ATM, Cafe...) are not available for translation. They are cryptic in English.
- Whogo Maps has a translatable word in it but is not in transifex.

**Comment by otsaloma** [comment]
OK, I'll release a translation update soon, weekend maybe.

> km / m should be translatable

Indeed, I'll make those translatable.

> Types of venues (ATM, Cafe...) are not available for translation. They are cryptic in English.

I might actually remove them entirely as they are supposed to be examples, but users seem to think it's the whole set of alternatives. Maybe a placeholder text works better there. Also, they can't just be freely translated as service provider APIs don't understand all languages.

> Whogo Maps has a translatable word in it but is not in transifex.

Indeed. It needs a build-time step to translate the desktop file, so I might leave it for later.

**Comment by otsaloma** [comment]
Units are now on Transifex, I'll wait a while before making a release.

**Comment by dikonov** [comment]
Thanks! It is fixed now.

**Comment by otsaloma** [comment]
Sorry, I missed the speed units, they are now at Transifex too.

**Comment by otsaloma** [comment]
1.0.1 released.
