### ISSUE TITLE
GPS loss while navigating

### ISSUE THREAD

**Issue by luchmhor** [otsaloma/whogo-maps#42]
Hey,

When driving through a (longer) tunnel while navigating the GPS signal is obviously lost and QtLocation delivers some "old" basic location, resulting in a jumping map.
Would it be possible to disable updating the location via QTLocation when driving through a tunnel (cheap solution), and maybe as a second step following the current road with the last known velocity until the end of the tunnel plus some buffer until a GPS fix (complex solution). The second step would also be very useful when in tunnels with branches or departures.

Cheers.

**Comment by otsaloma** [comment]
I don't see any tunnel special-casing or road-following being realistic. The only thing I can think of is to not auto-center when the positioning accuracy is above some given threshold. But I don't know how much that would help and it has its own problems and would need proper field-testing.

**Comment by luchmhor** [comment]
Thanks for the fast response.

Maybe it would be possible to check the "tunnel tag": https://wiki.openstreetmap.org/wiki/Key:tunnel for the actual section of the road?
