### ISSUE TITLE
ZeroDivisionError in calculate_segment_distance

### ISSUE THREAD

**Issue by rinigus** [otsaloma/whogo-maps#48]
While testing map matching, I was getting several times zero division error in the return statement

```
return seg_dist_deg * (med_dist_m / med_dist_deg)
```
of `calculate_segment_distance` in poor/util.py file. I presume that it was due to the fact that the map matched position was exactly on a segment and in a middle of it.

Not sure what's the best way to fix it though.

**Comment by otsaloma** [comment]
I guess your map matching is working as triggering this bug required very exact float values.

**Comment by rinigus** [comment]
Thank you for fixing it so fast! Yes, map matching does work and I am preparing a release with it.
