### ISSUE TITLE
Add support for day and night styles

### ISSUE THREAD

**Issue by rinigus** [otsaloma/whogo-maps#5]
I am filing it early since it may influence your design.

When driving, its good to have support for changing between day and night styles. Already now, Mapbox provides day/night traffic style, I am working on making the similar pair of styles for the server. Ideally, basemaps could be put in pairs for automatic switch in accordance with the local sunrise as well as colors used to render POIs, roads, menu button and texts with speed/scale. The latter could be done also with the assumption of light (day) and dark (night) backgrounds.

**Comment by otsaloma** [comment]
This seems to me a bigger issue as it, in addition to maps, would require inverse colors for all map overlays. I don't see it affecting design at this point, so it's an issue for much later, but good to keep in mind.
