### ISSUE TITLE
have an indicator for gps signal

### ISSUE THREAD

**Issue by legacychimera247** [otsaloma/whogo-maps#53]
it would be nice to have an indicator showing us how is the signal and/or it's hooked or not

just to give you some example on what i mean, jolla maps has a circle surrounding the pointer, that becomes smaller and smaller as the signal is stronger, or herewego as a flashing circle surrounding the pointer and when the signal is good it stop flashing and the pointer becomes green

it would be nice to have something like this...

**Comment by rinigus** [comment]
Not as sophisticated, but there is already an indicator of the GPS precision shown with ø at the bottom right corner of the map.

We had a circle in the early version of mapboxgl port, but it was removed to keep things simpler and not have large fraction of the map filled with it in the beginning of the session.

blinking / changing color - maybe. this would make sense when driving and not having much time to look for the number on the screen but preferring to get the readout with a glance.

**Comment by legacychimera247** [comment]
Ah well i never noticed that...i do assume that meters near that symbol is a precision indicator, right?

Il Lunedì 6 agosto 2018, rinigus scrive:
> Not as sophisticated, but there is already an indicator of the GPS precision shown with ø at the bottom right corner of the map.
> We had a circle in the early version of mapboxgl port, but it was removed to keep things simpler and not have large fraction of the map filled with it in the beginning of the session.
> blinking / changing color - maybe. this would make sense when driving and not having much time to look for the number on the screen but preferring to get the readout with a glance.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼

-- 
Inviato dal mio Jolla

**Comment by rinigus** [comment]
Yes, that's precision, right
