### ISSUE TITLE
FeatureRequest: auto_shorter 

### ISSUE THREAD

**Issue by ghost** [otsaloma/whogo-maps#55]
will nice to enable this option in whogo-maps, valhalla is supporting auto_shorter. I will contribute with beers and coffees to my request.
thanks.

**Comment by rinigus** [comment]
Same as with https://github.com/otsaloma/whogo-maps/issues/54:

I can work on it, seems to be rather trivial to add the support for. However, I would prefer the work on navigation that I have been doing to be merged first. Please wait a bit, we'll be able to add costing options in future.

**Comment by ghost** [comment]
good, thanks.
