### ISSUE TITLE
Show time remaining to destination

### ISSUE THREAD

**Issue by jaykijay** [otsaloma/whogo-maps#6]
Hi,
the old Pictures on Openrepos show the remaining time in the above right see here:
![grafik](https://user-images.githubusercontent.com/24495677/34642598-e2405d60-f315-11e7-9006-4473c49acc20.png)
Why is this gone? Or is it not gone and I#M to blind to see it? i never ever saw it while using the App for navigation. It would be very useful :)

**Comment by otsaloma** [comment]
It was removed on purpose in favor of the navigation status page that opens when you tap the black navigation block. There was too many numbers there and needed simplification to be clearer.

**Comment by jaykijay** [comment]
Okay i see you're all about purism ;) 
Is it possible to make such thinks configurable with a switch or something?
Things like this are a essential Feature for me, and all people I know. Not having this really kills the usefulness if i have to touch my smartphone to see at least how long i'l have to drive. For touching the phone i have to stop anywhere, because it's prohibited here and so this really needs to be seen on the main screen if someone wants it, i think ;)
Maybe make it like Here Maps, where you have disred places where you can configure which information should be displayed there.
For purism people this could be only the remaining kilometers where for people like me there will be many more things..
This would be really nice, but just make a switch to display the reamining time again would be nice for first fix :)
Hope you can somewhere understand what i mean :) 
Thanks for this really nice App ! One of the best Sailfish Apps i've ever used ;)

**Comment by otsaloma** [comment]
Configurability just leads to broken stuff as new features unavoidably will not be tested against all combinations. There'd need to be significant value to add such and regarding that navigation block, the closest to significant value is a separate landscape mode layout and even that's far from a priority.

What I could do is display time remaining to destination instead of distance. I don't remember why I chose to leave the distance of those two numbers.

**Comment by jaykijay** [comment]
Mh sad, i like customisation :D But i understand the point ;)
So if you don't like the idea why not revert to the old style? Did it hurt to show both values?
