### ISSUE TITLE
Make actual speed better visible

### ISSUE THREAD

**Issue by jaykijay** [otsaloma/whogo-maps#7]
Hey,
is it possible to make the actual speed:
![grafik](https://user-images.githubusercontent.com/24495677/34642613-36175196-f316-11e7-9e4b-512d19290ce5.png)
Better visible?
Maybe put it in the head and make it white like the remaining kilometers or something.
While driving it's very hard to see, at least for me ;)

By the way: What does the thing under it display? I didn't found out what it is used for..

**Comment by otsaloma** [comment]
It's not meant to be a big speedometer and it wouldn't be good use of available space to make it, so that's not going to happen.

The lower number is the positioning accuracy.

**Comment by jaykijay** [comment]
See #6 , maybe we can have a specific location where it's possible to configure the things that should be shown there and this things will be big enough to read ;)

Positioning accuracy: higher= better or lower= better?

**Comment by otsaloma** [comment]
For configurability, no, see #6.

> Positioning accuracy: higher= better or lower= better?

Lower is better. You're at most that shown distance from the position icon.
